### ISSUE TITLE
 SCTD2.0 can't download

### ISSUE THREAD

**Issue by 12345zqq** [freepoet/SCTD#10]
Dear Author 
I recently had the opportunity to read your paper, and I found your work to be highly insightful and valuable for my own research. However, I encountered an issue when trying to use the SCTD2.0 file from the dataset mentioned in your paper. Unfortunately, it seems that the file is unusable in its current form.
Could you kindly resend the SCTD2.0 file. My email is: 1094971428@qq.com

**Comment by MingqiangNing** [comment]
The file has been sent to your email.

**Comment by LF-begin** [comment]
Dear author:
I am honored to read your paper. Your research content is excellent and inspired me, and your data set is very valuable for my own research. However, I can't open the data set SCTD2.0 file in your link smoothly. Because the file seems to be unusable in its current form.
Could you resend the SCTD2.0 file? I will quote your research when I publish my paper in the future, and it will never be used for commercial purposes. My email is: 1781456629@qq.com.

**Comment by zhangbiao666** [comment]
Dear author:
I am honored to read your paper. Your research content is excellent and inspired me, and your data set is very valuable for my own research. However, I can't open the data set SCTD2.0 file in your link smoothly. Because the file seems to be unusable in its current form.
Could you resend the SCTD2.0 file? I will quote your research when I publish my paper in the future, and it will never be used for commercial purposes. My email is: 1653112782@qq.com.

**Comment by MingqiangNing** [comment]
The dataset has been sent via my QQ email, please check it.
________________________________

**Comment by lsfyolo** [comment]
尊敬的作者：
我很荣幸能阅读您的论文。您的研究内容非常出色，启发了我，您的数据集对我自己的研究非常有价值。但是，我无法顺利打开您链接中的数据集 SCTD2.0 文件。因为该文件在当前形式下似乎无法使用。
您能否重新发送 SCTD2.0 文件？我将在未来发表论文时引用您的研究，绝不会用于商业目的。我的电子邮件是：[760196893@qq.com)。

**Comment by MingqiangNing** [comment]
> 尊敬的作者： 我很荣幸能阅读您的论文。您的研究内容非常出色，启发了我，您的数据集对我自己的研究非常有价值。但是，我无法顺利打开您链接中的数据集 SCTD2.0 文件。因为该文件在当前形式下似乎无法使用。 您能否重新发送 SCTD2.0 文件？我将在未来发表论文时引用您的研究，绝不会用于商业目的。我的电子邮件是：[[760196893@qq.com](mailto:760196893@qq.com))。

The dataset has been sent via QQ email. Please refer to the email attachment for details.

**Comment by liveonearthormars** [comment]
尊敬的作者：
我很荣幸能阅读您的论文。您的研究内容非常出色，启发了我，您的数据集对我自己的研究非常有价值。但是，我无法顺利打开您链接中的数据集 SCTD2.0 文件。因为该文件在当前形式下似乎无法使用。
您能否重新发送 SCTD2.0 文件？我将在未来发表论文时引用您的研究，绝不会用于商业目的。我的电子邮件是：1435627164@qq.com

**Comment by MingqiangNing** [comment]
已经通过QQ邮箱发送，请查看附件。
________________________________
